

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";




CREATE TABLE IF NOT EXISTS `log_actions` (
  `id` int(11) NOT NULL,
  `la_action_name` varchar(250) NOT NULL,
  `la_points` int(11) NOT NULL,
  `la_message` text NOT NULL,
  `la_controller` varchar(250) NOT NULL
) ENGINE=InnoDB AUTO_INCREMENT=255 DEFAULT CHARSET=latin1;



INSERT INTO `log_actions` (`id`, `la_action_name`, `la_points`, `la_message`, `la_controller`) VALUES
(1, 'Question Creation', 0, '{username} has added a question in {site_name}', 'question_added'),
(2, 'Question Updation', 0, '{username} has updated a question in {site_name}', 'question_updated'),
(3, 'Question Deletion', 0, '{username} has deleted {count} in {site_name}', 'question_deleted'),
(4, 'Question Import', 0, '{username} has imported {count} in {site_name}', 'question_imported'),
(5, 'Faculty Creation', 0, '{username} has added a faculty in {site_name}', 'faculty_created'),
(6, 'Faculty Import', 0, '{username} has imported {count} in {site_name}', 'faculties_imported'),
(7, 'Faculty Updation', 0, '{username} has updated a faculty in {site_name}', 'faculty_updated'),
(8, 'Faculty Deletion', 0, '{username} has deleted {count} in {site_name}', 'faculty_deleted'),
(9, 'Faculty Restore', 0, '{username} has restored a faculty in {site_name}', 'faculty_restored'),
(10, 'Faculty Activation', 0, '{username} has activated {count} in {site_name}', 'faculty_activated_bulk'),
(11, 'Faculty Deactivation', 0, '{username} has deactivated {count} in {site_name}', 'faculty_deactivated_bulk'),
(12, 'Faculty password reset', 0, '{username} has reset a faculty password in {site_name}', 'faculty_password_reset'),
(13, 'Batch Creation', 0, '{username} has created the batch {batch} in {site_name}', 'batch_created'),
(14, 'Batch Updation', 0, '{username} has updated the batch {batch} in {site_name}', 'batch_updated'),
(15, 'Batch Deletion', 0, '{username} has deleted the batch {batch} from {site_name}', 'batch_deleted'),
(16, 'Student added in batch', 0, '{username} has added {count} to batch {batch_name} in {site_name}', 'student_added_to_batch'),
(17, 'Students remove from batch', 0, '{username} has removed {count} from batch {batch_name} in {site_name}', 'student_removed_from_batch'),
(18, 'Institute Creation', 0, '{username} has added the institute {institute} in {site_name}', 'institute_created'),
(19, 'Institute Update', 0, '{username} has updated the institute {institute} in {site_name}', 'institute_updated'),
(20, 'Institute Delete', 0, '{username} has deleted the institute {institute} in {site_name}', 'institute_deleted'),
(21, 'Institute Restore', 0, '{username} has restored the institute {institute} in {site_name}', 'institute_restored'),
(22, 'Institute Activate', 0, '{username} has activated the institute {institute} in {site_name}', 'institute_activated'),
(23, 'Institute Deactivate', 0, '{username} has deactivated the institute {institute} in {site_name}', 'institute_deactivated'),
(24, 'Institute Bulk Delete ', 0, '{username} has deleted {count} in {site_name}', 'institute_deleted_bulk'),
(25, 'Institute Bulk Activate', 0, '{username} has activated {count} in {site_name}', 'institute_activated_bulk'),
(26, 'Institute Bulk Deactivate', 0, '{username} has deactivated {count} in {site_name}', 'institute_deactivated_bulk'),
(28, 'Institute Import', 0, '{username} has imported {count} in {site_name}', 'institutes_imported'),
(29, 'Student Creation', 0, '{username} has added the student {student} in {site_name}', 'student_created'),
(30, 'Student Approval', 0, '{username} has approved the student {student} in {site_name}', 'student_account_approved'),
(31, 'Student Activation', 0, '{username} has activated the student {student} in {site_name}', 'student_activated'),
(32, 'Student Deactivation', 0, '{username} has deactivated the student {student} in {site_name}', 'student_deactivated'),
(33, 'Student Approval Bulk', 0, '{username} has approved {count} in {site_name}', 'student_account_approved_bulk'),
(34, 'Student Bulk Activation ', 0, '{username} has activated {count} in {site_name}', 'student_activated_bulk'),
(35, 'Student Bulk Deactivation', 0, '{username} has deactivated {count} in {site_name}', 'student_deactivated_bulk'),
(36, 'Student Deletion', 0, '{username} has deleted the student {student} in {site_name}', 'student_deleted'),
(37, 'Student Bulk Deletion', 0, '{username} has deleted {count} in {site_name}', 'student_deleted_bulk'),
(38, 'Student Restore', 0, '{username} has restored the student {student} in {site_name}', 'student_restored'),
(39, 'Student Import', 0, '{username} has imported {count} in {site_name}', 'student_imported'),
(40, 'Student Profile View', 0, '{username} has viewed the student {student} in {site_name}', 'student_profile_viewes'),
(41, 'Student Batch Subscription', 0, '{username} has added the student {student} to {count} in {site_name}', 'add_student_to_batch'),
(42, 'Student Profile Update', 0, '{username} has updated the profile of the student {student} in {site_name}', 'student_profile_updated'),
(43, 'Category Creation', 0, '{username} has added {categories} in {site_name}', 'category_created'),
(44, 'Category Update', 0, '{username} has updated the category {category} in {site_name}', 'category_updated'),
(45, 'Category Delete', 0, '{username} has deleted the category {category} in {site_name}', 'category_deleted'),
(46, 'Category Migrate', 0, '{username} has migrated the category {migrate}  in {site_name}', 'category_migrated'),
(47, 'Subject Creation', 0, '{username} has added {subjects} under the category {category} in {site_name}', 'sub_category_created'),
(48, 'Subject Update', 0, '{username} has updated the subject {subject} under the category {category} in {site_name}', 'sub_category_updated'),
(49, 'Subject Delete', 0, '{username} has deleted the subject {subject} under the category {category} in {site_name}', 'sub_category_deleted'),
(50, 'Subject Merge', 0, '{username} has merged {subjects} under the category {category} in {site_name}', 'sub_category_merged'),
(51, 'Topic Creation', 0, '{username} has added {topics} under the category  {category} and subject {subject} in {site_name}', 'topics_created'),
(52, 'Topic Update', 0, '{username} has updated the topic {topic} under the category  {category} and subject {subject}  in {site_name}', 'topics_updated'),
(53, 'Topic Deletion', 0, '{username} has deleted the topic {topic} under the category {category} and subject {subject} in {site_name}', 'topics_deleted'),
(54, 'Topics Merge', 0, '{username} has merged {topics} under the category  {category} and subject {subject} in {site_name}', 'topics_merged'),
(55, 'Report Generation', 0, '{username} has generated the {report} report in {site_name}', 'report_generated'),
(57, 'Login', 0, '{username} logged into {site_name}', 'user_login'),
(60, 'Forgot Password', 0, '{username} requested to change password', 'forgot_password'),
(63, 'Logout', 0, '{username} logged out of {site_name}', 'user_logout'),
(66, 'Student Registration', 10, '{username} has created an account in {site_name}', 'student_registered'),
(69, 'Student subscribed to course', 25, '{username} subscribed to course{course_name}', 'course_subscribed'),
(72, 'Student changed profile image', 5, '{username} changed profile picture', 'student_profile_picture_changed'),
(75, 'Student changed password', 0, '{username} changed password', 'student_password_changed'),
(78, 'Student added email id', 5, '{username} updated email id {email_id}', 'student_email_id_changed'),
(81, 'Student changed register number', 0, '{username} updated register number {register_number} ', 'student_register_number_changed'),
(84, 'Student changed value for dyanmic fileds', 0, '{username} updated profile info', 'student_profile_data_changed'),
(87, 'Student submit an assignment', 10, '{username} submitted assignment {assignment_title} in the course {course_name}', 'assignment_submitted'),
(90, 'Student submit an Quiz', 10, '{username} submitted quiz {quiz_title} in the course {course_name}', 'quiz_submitted'),
(93, 'Student submit an Survey', 10, '{username} submitted survey {survey_title} in the course {course_name}', 'survey_submitted'),
(96, 'Student answered a post', 5, '{username} answered for the post {post_name}', 'post_answered'),
(99, 'Student likes a post', 5, '{username} liked the post {post_name}', 'post_liked'),
(102, 'Course rated', 5, '{username} rated course {course_name}', 'course_rated'),
(105, 'Video lecture completed', 5, '{username} completed the video lecture {lecture_name}', 'video_lecture_completed'),
(108, 'Document lecture completed', 5, '{username} completed the lecture {lecture_name}', 'document_lecture_completed'),
(111, 'Live class attended', 50, '{username} attended the live lecture {lecture_name}', 'live_attended'),
(114, 'Course shared by student', 20, '{username} shared the course {course_name}', 'course_shared'),
(117, 'Course certificate generated by student', 0, '{username} generated the certificate for course {course_name}', 'course_certificate_generated'),
(120, 'Admin/Privileged User creates a course', 0, '{username} created a course {course_name}', 'course_created'),
(123, 'Admin/Privileged User activates a course', 0, '{username} activated the course {course_name}', 'course_activated'),
(126, 'Admin/Privileged User deactivates a course', 0, '{username} deactivated the course {course_name}', 'course_deactivated'),
(129, 'Admin/Privileged User deleted a course', 0, '{username} deleted the course {course_name}', 'course_deleted'),
(132, 'Admin/Privileged User restore a course', 0, '{username} restored the course {course_name}', 'course_restore'),
(135, 'Admin/Privileged User creates a section', 0, '{username} created section {section_name} in course {course_name}', 'section_created'),
(138, 'Admin/Privileged User updated a section details', 0, '{username} updated section {section_name} details in course {course_name}', 'section_updated'),
(141, 'Admin/Privileged User activates a section', 0, '{username} activated the section {section_name} in {course_name}', 'section_activated'),
(144, 'Admin/Privileged User deactivates a section', 0, '{username} deactivated the section {section_name} in {course_name} ', 'section_deactivated'),
(147, 'Admin/Privileged User deletes a section', 0, 'Section {section_name} in course {course_name} has been deleted by {username}.', 'section_deleted'),
(150, 'Admin/Privileged User activates a lecture', 0, '{username} activated the lecture {lecture_name} in course {course_name}', 'lecture_activated'),
(153, 'Admin/Privileged User deactivates a lecture', 0, '{username} deactivated the lecture {lecture_name} in course {course_name}', 'lecture_deactivated'),
(156, 'Admin/Privileged User deletes a lecture', 0, '{username} deleted the lecture {lecture_name} in course {course_name}', 'lecture_deleted'),
(159, 'Admin/Privileged User creates a lecture', 0, '{username} created the lecture {lecture_name} in course {course_name}', 'lecture_created'),
(162, 'Student subscribed to course by Admin/Privileged ', 0, '{username} added {student} to {count} course {course_name}', 'admin_user_subscribe'),
(165, 'Admin/Privileged suspended course subscription of single user', 0, '{username} suspended subscription of {student} from course {course_name}', 'course_subscription_suspended'),
(168, 'Admin/Privileged User approved course subscription of single student', 0, '{username} approved subscription of {student} from course {course_name}', 'course_subscription_approved'),
(171, 'When Admin/Privileged User add/update an Announcement', 0, '{username} {action} the announcement  {announcement_title}', 'course_announcement'),
(174, 'When Admin/Privileged User deleted an Announcement', 0, '{username} deleted the announcement {announcement_title}', 'course_announcement_deleted'),
(177, 'When Admin/Privileged User updated course settings and details under advanced tab', 0, '{username} has updated the course settings of {course_name}', 'course_updated'),
(180, 'When Admin/Privileged User assign a faculty to course', 0, '{username} {action} {count} faculty to the course {course_name}', 'faculty_assigned_to_course'),
(183, 'Admin changed his profile details', 0, '{username} changed his profile info', 'admin_profile_data_changed'),
(186, 'Changing basic settings', 0, '{username} updated Basic settings.', 'basic_settings_updated'),
(189, 'Upload new banner', 0, '{username} uploaded a new banner', 'banner_upload'),
(192, 'New profile field added', 0, '{username} {action} the profile field {field_label}', 'profile_field_added'),
(195, 'New Certificate uploaded', 0, '{username} uploaded a certificate', 'certificate_uploaded'),
(198, 'Admin/Privileged User created,update,delete role', 0, '{username} {action} the role {role}', 'role_operation'),
(201, 'Updated email template details', 0, '{username} updated the email template {template_name}', 'email_template_updated'),
(204, 'Admin/Privileged User suspended/activate course subscription of bulk user', 0, '{username} has {action} subscription of {count} students in course {course_name}', 'course_subscription_status_bulk'),
(207, 'Student removed from course by Admin/Privileged ', 0, '{username} removed the subscription of {count} student {student_name} from course {course_name}', 'course_subscription_removed'),
(210, 'Course validity change for students by Admin/Privileged User', 0, '{username} changed the subscription validity of {count} student {student_name} in course {course_name}', 'course_subscription_validity_changed'),
(213, 'Admin/Privileged User set course completed for student', 0, '{username} set the subscription completed for {count} student {student_name} in course {course_name}', 'course_set_as_complete'),
(216, 'Admin/Privileged User reset course activities of student', 0, '{username} reset the result of {count} student {student_name} in course {course_name}', 'course_result_reset'),
(219, 'Admin/Privileged User blocked forum access of student', 0, '{username} {action} the access of forum of student {student_name} in course {course_name}', 'course_forum_access'),
(222, 'Admin/Privileged User set course completed for batch', 0, '{username} set the subscription completed for {count} students under {batch_count} batch {batch_name} in course {course_name}', 'course_set_as_complete_group'),
(225, 'Admin/Privileged User reset logs for a students for batch', 0, '{username} reset the result for {count} students under {batch_count} batch {batch_name} in course {course_name}', 'course_result_reset_group'),
(228, 'Admin/Privileged removed batch from course', 0, '{username} removed the subscription of {count} students under {batch_count} batch {batch_name} in course {course_name}', 'course_subscription_removed_group'),
(231, 'Admin/Privileged changed course subscription status of single batch', 0, '{username} {action} subscription of {count} students under batch {batch_name} in course {course_name}', 'course_subscription_status_batch'),
(234, 'Students subscribed to course by Admin/Privileged ', 0, '{username} enrolled {count} student to course {course_name}\n', 'admin_users_subscribe_course'),
(237, 'When Admin/Privileged User create an Event', 0, '{username} has {action} the event {event_name} in {site_name}', 'event'),
(238, 'Student subscribed to bundle', 25, '{username} subscribed to bundle{bundle_name}', 'bundle_subscribed'),
(239, 'Students subscribed to bundle by Admin/Privileged ', 0, '{username} enrolled {count} student to bundle {bundle_name} ', 'admin_users_subscribe_bundle'),
(240, 'Category Activated', 0, '{username} has activated the category {category_name}', 'category_activated'),
(241, 'Category Deactivated', 0, '{username} has deactivated the category {category_name}', 'category_deactivated'),
(242, 'Student answered the question', 5, '{username} answered for the question {post_name}', 'question_answered'),
(243, 'Student created the question', 0, '{username} created the question {post_name} under the course {course_name}', 'question_created'),
(244, 'Bundle rated', 5, '{username} rated bundle {bundle_name}', 'bundle_rated'),
(245, 'When Admin/Privileged User updated course settings and details under advanced tab', 0, '{username} has updated the course seo settings of {course_name}', 'course_advanced_updated'),
(246, 'When Admin/Privileged User enrolled new bundles to the course batch enroll tab', 0, '{username} has enrolled new batches(s) "{group_string}" to the course {course_name}', 'batch_enrolled_to_course'),
(248, 'when questions are created', 0, 'A question "{post_name}" id edited by {username} under the course {course_name}.', 'question_edited'),
(249, 'when batch set as complete in course groups tab', 0, 'A batch "{batch_name}" set as complete by {username} under the course {course_name}', 'course_set_as_complete_batch'),
(250, 'when batch set as complete in course groups tab', 0, 'A batch "{batch_name}" course result reset by {username} under the course {course_name}', 'course_result_reset_batch'),
(251, 'Admin/Privileged User deleted a course', 0, '{username} permenently deleted the course {course_name}', 'course_permanently_deleted'),
(252, 'Student changed profile image', 0, '{username} changed profile picture', 'student_profile_picture_changed_zero'),
(253, 'Student added email id', 0, '{username} updated email id {email_id}', 'student_email_id_changed_zero'),
(254, 'Student changed phone number', 0, '{username} updated phone number {phone_number}', 'student_phone_number_changed');



CREATE TABLE IF NOT EXISTS `log_activity` (
  `id` int(11) NOT NULL,
  `la_account_id` int(11) NOT NULL DEFAULT '0',
  `la_user_id` int(11) NOT NULL,
  `la_user_name` varchar(255) DEFAULT NULL,
  `la_user_email` varchar(255) NOT NULL,
  `la_phone_number` varchar(250) DEFAULT NULL,
  `la_usertype` int(11) NOT NULL,
  `la_action` varchar(250) NOT NULL,
  `la_message` text NOT NULL,
  `la_created_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `la_ip_address` varchar(255) DEFAULT NULL,
  `la_points` int(11) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;



CREATE TABLE IF NOT EXISTS `log_activity_points` (
  `id` int(11) NOT NULL,
  `lap_account_id` int(11) NOT NULL DEFAULT '0',
  `lap_user_id` int(11) NOT NULL DEFAULT '0',
  `lap_user_name` varchar(255) DEFAULT NULL,
  `lap_user_points` int(11) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;