SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";




CREATE TABLE IF NOT EXISTS `course_backups` (
  `id` int(11) NOT NULL,
  `cbk_course_name` varchar(255) DEFAULT NULL,
  `cbk_course_code` varchar(5) DEFAULT NULL,
  `cbk_course_id` int(11) NOT NULL DEFAULT '0',
  `cbk_assets` text,
  `cbk_size` varchar(50) DEFAULT NULL,
  `cbk_backup_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `cbk_account_id` int(11) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

CREATE TABLE IF NOT EXISTS `course_basics` (
  `id` int(11) NOT NULL,
  `cb_title` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `cb_description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `cb_discussion_instruction` longtext,
  `cb_position` int(11) NOT NULL,
  `cb_code` varchar(50) DEFAULT NULL,
  `cb_category` varchar(200) NOT NULL,
  `cb_is_free` enum('1','0') NOT NULL DEFAULT '0',
  `cb_access_validity` enum('0','1','2') NOT NULL DEFAULT '0',
  `cb_has_self_enroll` enum('0','1') NOT NULL DEFAULT '0',
  `cb_self_enroll_date` date DEFAULT NULL,
  `cb_preview` enum('1','0') NOT NULL DEFAULT '1',
  `cb_preview_time` int(11) NOT NULL DEFAULT '300',
  `cb_has_certificate` enum('1','0') NOT NULL DEFAULT '0',
  `cb_has_renewal` enum('0','1') NOT NULL DEFAULT '0',
  `cb_need_percentage` int(11) NOT NULL,
  `cb_price` int(11) NOT NULL DEFAULT '0',
  `cb_discount` int(11) NOT NULL DEFAULT '0',
  `cb_tax_method` int(11) NOT NULL,
  `cb_validity` int(11) NOT NULL,
  `cb_validity_date` date DEFAULT NULL,
  `cb_promo` varchar(255) NOT NULL,
  `cb_image` varchar(255) NOT NULL DEFAULT 'default.jpg',
  `cb_language` varchar(200) NOT NULL,
  `cb_slug` varchar(255) NOT NULL,
  `cb_route_id` int(11) NOT NULL,
  `cb_virtual_class` enum('1','0') NOT NULL DEFAULT '0',
  `cb_virtual_room` int(11) DEFAULT NULL,
  `cb_meta` text NOT NULL,
  `cb_meta_description` text NOT NULL,
  `cb_video_count` int(11) NOT NULL DEFAULT '0',
  `cb_docs_count` int(11) NOT NULL DEFAULT '0',
  `cb_live_count` int(11) NOT NULL DEFAULT '0',
  `cb_assessment_count` int(11) NOT NULL DEFAULT '0',
  `cb_video_duration` double NOT NULL DEFAULT '0' COMMENT 'Duration in secs.',
  `cb_has_lecture_image` int(5) NOT NULL DEFAULT '0' COMMENT '''0=>''no lecture image'',''1''=>"lecture image"',
  `cb_status` enum('1','0','2') NOT NULL DEFAULT '0',
  `cb_approved` enum('0','1') NOT NULL DEFAULT '0',
  `cb_deleted` enum('1','0') NOT NULL DEFAULT '0',
  `cb_account_id` int(11) NOT NULL,
  `cb_groups` text NOT NULL,
  `cb_course_likes` int(11) NOT NULL DEFAULT '0',
  `cb_course_dislikes` int(11) NOT NULL DEFAULT '0',
  `cb_course_forum_likes` int(11) NOT NULL DEFAULT '0',
  `cb_course_forum_dislikes` int(11) NOT NULL DEFAULT '0',
  `cb_total_enrolled_users` int(11) NOT NULL DEFAULT '0',
  `cb_course_completed_count` int(11) NOT NULL DEFAULT '0',
  `cb_created_by` int(11) NOT NULL DEFAULT '0',
  `action_id` int(11) NOT NULL,
  `action_by` int(11) NOT NULL,
  `created_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_date` datetime DEFAULT '2019-09-02 12:10:44',
  `cb_short_description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `cb_total_video_hours` varchar(20) NOT NULL DEFAULT '0',
  `cb_what_u_get` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `cb_requirements` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `cb_has_rating` enum('0','1') NOT NULL DEFAULT '0',
  `cb_has_show_total_enrolled` enum('0','1') NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=latin1;